Repository ssginc-be/NoJam, pull requests merged in 2025-01, with the labels that each got.

#3 상품 크롤러 구현
  build.gradle
  src/main/java/com/ssginc/nojam/crawl/NoBrandItemCrawler.java
  src/main/java/com/ssginc/nojam/crawl/controller/CrawlerController.java
  src/main/java/com/ssginc/nojam/crawl/mapper/CrawlerMapper.java
  src/main/java/com/ssginc/nojam/crawl/service/CrawlerService.java
  src/main/java/com/ssginc/nojam/crawl/vo/ItemVO.java
  src/main/resources/mapper/crawlerMapper.xml
Labels: crawl

#10 회원가입 기능 구현
  src/main/java/com/ssginc/nojam/config/EncryptionConfig.java
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/member/mapper/MemberMapper.java
  src/main/java/com/ssginc/nojam/member/service/MemberService.java
  src/main/java/com/ssginc/nojam/member/vo/MemberVO.java
  src/main/resources/applicationContext.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/templates/index.html
  src/main/resources/templates/member/register.html
  src/main/resources/templates/member/signup.html
Labels: feat, ui

#13 크롤러 카테고리 지정 방식 수정
  src/main/java/com/ssginc/nojam/crawl/NoBrandItemCrawler.java
Labels: crawl

#14 로그인/로그아웃 기능 구현
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/member/service/MemberService.java
  src/main/resources/templates/index.html
Labels: feat, ui

#16 회원가입 SMTP 기능 구현
  build.gradle
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/member/service/EmailService.java
  src/main/resources/application.properties
  src/main/resources/templates/member/signup.html
Labels: feat, ui

#19 카테고리별 상품 판매량 API 구현
  src/main/java/com/ssginc/nojam/chart/controller/ChartController.java
  src/main/java/com/ssginc/nojam/chart/mapper/ChartMapper.java
  src/main/java/com/ssginc/nojam/chart/service/ChartService.java
  src/main/java/com/ssginc/nojam/chart/vo/GetBranchIdAndNameDto.java
  src/main/resources/mapper/chartMapper.xml
  src/main/resources/static/js/demo/barChart.js
  src/main/resources/templates/chart/chart.html
Labels: feat, ui

#21 공통 UI 수정
  src/main/resources/static/css/layout.css
  src/main/resources/static/img/WNobrandIcon.png
  src/main/resources/static/img/logout.png
  src/main/resources/static/img/user.jpg
  src/main/resources/static/js/layout.js
  src/main/resources/templates/layout.html
Labels: ui

#23 로그인/회원가입 UI 보수
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/img/no-brand-store.jpg
  src/main/resources/static/img/nobrand-logo1.png
  src/main/resources/static/img/nobrand-logo2.png
  src/main/resources/templates/index.html
  src/main/resources/templates/index0.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/member/signup0.html
Labels: feat, ui

#27 SMTP 설정 smtp.properties 파일 분리
  .gitignore
  src/main/resources/application.properties
Labels: feat

#30 지점별 입고 대비 판매량 차트 API 구현
  src/main/java/com/ssginc/nojam/chart/controller/ChartController.java
  src/main/java/com/ssginc/nojam/chart/mapper/ChartMapper.java
  src/main/java/com/ssginc/nojam/chart/service/ChartService.java
  src/main/resources/mapper/chartMapper.xml
  src/main/resources/static/js/demo/areaChart.js
  src/main/resources/static/js/demo/barChart.js
  src/main/resources/templates/chart/chart.html
Labels: feat, ui

#31 지점 재고 조회 기능 구현
  src/main/java/com/ssginc/nojam/stock/controller/StockController.java
  src/main/java/com/ssginc/nojam/stock/dto/BranchStockViewDTO.java
  src/main/java/com/ssginc/nojam/stock/mapper/StockMapper.java
  src/main/resources/mapper/stockMapper.xml
  src/main/resources/templates/stock/branch-view-query.html
  src/main/resources/templates/stock/branch-view.html
Labels: feat, ui

#37 비밀번호 찾기 SMTP 기능 구현
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/member/mapper/MemberMapper.java
  src/main/java/com/ssginc/nojam/member/service/EmailService.java
  src/main/java/com/ssginc/nojam/member/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/static/css/find-pw.css
  src/main/resources/templates/index.html
  src/main/resources/templates/member/find-pw.html
  src/main/resources/templates/member/signup.html
Labels: feat, ui

#35 지점 정보 조회 기능 구현
  src/main/java/com/ssginc/nojam/system/controller/MapController.java
  src/main/java/com/ssginc/nojam/system/mapper/MapMapper.java
  src/main/java/com/ssginc/nojam/system/service/MapService.java
  src/main/java/com/ssginc/nojam/system/vo/MapVO.java
  src/main/resources/mapper/MapMapper.xml
  src/main/resources/static/css/map.css
  src/main/resources/static/js/map.js
  src/main/resources/templates/system/map.html
Labels: feat, ui

#42 회원가입 시 이메일 중복 검사 기능 구현
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/member/service/MemberService.java
  src/main/resources/templates/member/signup.html
Labels: bug, feat, ui

#45 요일별 지점 판매량 차트 API 구현
  src/main/java/com/ssginc/nojam/chart/controller/ChartController.java
  src/main/java/com/ssginc/nojam/chart/mapper/ChartMapper.java
  src/main/java/com/ssginc/nojam/chart/service/ChartService.java
  src/main/java/com/ssginc/nojam/chart/vo/GetSalesAndDateDto.java
  src/main/resources/mapper/chartMapper.xml
  src/main/resources/static/css/calendar.css
  src/main/resources/static/js/demo/lineChart.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/chart/chart.html
Labels: feat, ui

#48 대시보드 카드 API 구현
  src/main/java/com/ssginc/nojam/chart/controller/ChartController.java
  src/main/java/com/ssginc/nojam/chart/mapper/ChartMapper.java
  src/main/java/com/ssginc/nojam/chart/service/ChartService.java
  src/main/resources/mapper/chartMapper.xml
  src/main/resources/static/js/card.js
  src/main/resources/templates/chart/chart.html
Labels: feat, ui

#52 각 출고 상태 비율 차트 API 구현
  src/main/java/com/ssginc/nojam/chart/controller/ChartController.java
  src/main/java/com/ssginc/nojam/chart/mapper/ChartMapper.java
  src/main/java/com/ssginc/nojam/chart/service/ChartService.java
  src/main/java/com/ssginc/nojam/chart/vo/GetStatusAndCountDto.java
  src/main/java/com/ssginc/nojam/chart/vo/GetStatusAndPercentageDto.java
  src/main/resources/mapper/chartMapper.xml
  src/main/resources/static/js/demo/pieChart.js
  src/main/resources/templates/chart/chart.html
Labels: feat, ui

#55 사이드바 메뉴별 페이지 연결 및 유기적 통합
  src/main/java/com/ssginc/nojam/member/controller/MemberController.java
  src/main/java/com/ssginc/nojam/outgoing/controller/OutgoingController.java
  src/main/java/com/ssginc/nojam/outgoing/mapper/OutgoingMapper.java
  src/main/resources/mapper/outgoingMapper.xml
  src/main/resources/static/css/layout.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/map.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/css/update-mypage.css
  src/main/resources/static/img/WNobrandIcon.png
  src/main/resources/static/img/logout-icon.svg
  src/main/resources/static/img/nojam-logo.svg
  src/main/resources/static/img/user-profile-2.png
  src/main/resources/static/img/user-profile.png
  src/main/resources/static/img/user.jpg
  src/main/resources/static/img/welcome-bg.png
  src/main/resources/static/js/layout.js
  src/main/resources/templates/chart/chart.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/member/update-mypage.html
  src/main/resources/templates/order/upload.html
  src/main/resources/templates/outgoing/indelivery.html
  src/main/resources/templates/outgoing/pending.html
  src/main/resources/templates/outgoing/view.html
  src/main/resources/templates/stock/branch-view-query.html
  src/main/resources/templates/stock/branch-view.html
  src/main/resources/templates/stock/head-view-query.html
  src/main/resources/templates/stock/head-view.html
  src/main/resources/templates/system/map.html
Labels: bug, feat, ui
